version: "3.7"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d
      - socket-vol:/var/run/socks
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./etc/redis/redis.conf:/etc/redis.conf
      - redis-vol:/data
      - socket-vol:/var/run/socks
  node:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ../:/src
      - socket-vol:/var/run/socks
    working_dir: /src
    command: yarn start
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: test
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql/data
  #     - socket-vol:/var/run/postgresql
  #   ports:
  #     - 5432:5432
volumes:
  postgresql-vol:
  socket-vol:
  redis-vol:
