version: "3.7"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d
      - /tmp:/var/run/socks
    restart: always
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./etc/redis/redis.conf:/etc/redis.conf
      - redis-vol:/data
      - /tmp:/var/run/socks
    restart: always
  node:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ../:/src
      - /tmp:/var/run/socks
      - node_modules-vol:/src/node_modules
    restart: always
    working_dir: /src
    command: >
      bash -c "yarn && yarn build && yarn start"
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: test
  #   restart: always
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql/data
  #     - /tmp:/var/run/postgresql
  #   ports:
  #     - 5432:5432
volumes:
  postgresql-vol:
  redis-vol:
  node_modules-vol:
