name: VisualTest(push)
on:
  push:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: xbrowser-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: xbrowser-yarn-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build test
        run: |
          # yarn build
      - name: Create capture
        env:
          STORYBOOK_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: yarn capture
      - name: Save capture
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          BRANCH=`echo $GITHUB_REF | sed 's/^refs\/heads\///'`
          cd __screenshots__
          git init
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${GITHUB_ACTOR}@git
          git checkout -b captures/$BRANCH
          git add .
          git commit -m $BRANCH
          git push -f origin captures/$BRANCH
